volumes:
  api-msql:
    name: api_msql_001
services:
    mysql:
        image: 'mysql:8.0'
        container_name: 'api_msql_001'
        working_dir: /application
        volumes:
            - api-msql:/application
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${PORT_MSQL}:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: 'api_phpmyadmin_001'
        ports:
            - ${PORT_PHP}:80
        environment:
            - PMA_ARBITRARY=1
    webserver:
        image: 'nginx:alpine'
        container_name: 'api_webserver_001'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - ${PORT_WEBSERVER}:80
    php-fpm:
        build: phpdocker/php-fpm
        container_name: 'api_fpm_001'
        working_dir: /application
        volumes:
            - .:/application
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'